# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gh-combine
    env:
      - CGO_ENABLED=0
      - GOPROXY=off
      - GOSUMDB=off
      - SOURCE_DATE_EPOCH={{ .CommitTimestamp }}
    flags:
      - -trimpath
      - -mod=vendor
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/github/gh-combine/internal/version.tag={{.Tag}} -X github.com/github/gh-combine/internal/version.commit={{.FullCommit}} -X github.com/github/gh-combine/internal/version.buildTime={{.Date}}

archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

release:
  draft: false

dist: "./dist"
