#! /usr/bin/env bash

set -e

# if the tparse binary is not found, don't use it
if ! command -v tparse &> /dev/null; then
  go test -v -cover ./...
else
  set -o pipefail && go test -cover -coverprofile=coverage.out -json ./... | tparse -all -trimpath github.com/github/
fi
